os:
- linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libssl-dev
language: rust
rust:
- nightly
cache: cargo

before_script:
# install code coverage tool
- RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin

script:
- cargo test --release
- RUST_BACKTRACE=1 cargo tarpaulin -v --out Xml
